# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['stage']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4

      - name: Show Environments
        run: |
          echo "SSH_KEY $SSH_KEY"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: 52.78.111.104
          username: bitnami
          port: 22
          key: $SSH_KEY
          script: |
            echo "test"
            cd ~/apps/testGitAction
            git pull
            npm ci
            npm run prisma
            npm build
            pm2 reload ecosystem.config.js
